name: 'build-push-clean'

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_FULL }}

      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . -t ghcr.io/chronon/webhook-docker-compose:latest

      - name: Push the Docker image
        run: docker push ghcr.io/chronon/webhook-docker-compose:latest 

      - name: Delete old package versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'webhook-docker-compose'
          package-type: 'container'
          min-versions-to-keep: 5
          token: ${{ secrets.PACKAGES_FULL }}
